[package]
name = "halbu"
version = "0.1.0"
edition = "2021"
authors = ["feor"]

[dependencies]
bit = "0.1.1"
serde = {version = "1.0.177", features = ["derive"]}
serde_with = "3.1.0"
unicode-segmentation = "1.10.1"
