use super::*;

pub const VARIANTS: [Variant; 39] = [
    Variant(Class::Rogue(Rogue::Fire), Difficulty::Normal),
    Variant(Class::Rogue(Rogue::Cold), Difficulty::Normal),
    Variant(Class::Rogue(Rogue::Fire), Difficulty::Nightmare),
    Variant(Class::Rogue(Rogue::Cold), Difficulty::Nightmare),
    Variant(Class::Rogue(Rogue::Fire), Difficulty::Hell),
    Variant(Class::Rogue(Rogue::Cold), Difficulty::Hell),
    Variant(Class::DesertMercenary(DesertMercenary::Prayer), Difficulty::Normal),
    Variant(Class::DesertMercenary(DesertMercenary::Defiance), Difficulty::Normal),
    Variant(Class::DesertMercenary(DesertMercenary::BlessedAim), Difficulty::Normal),
    Variant(Class::DesertMercenary(DesertMercenary::Thorns), Difficulty::Nightmare),
    Variant(Class::DesertMercenary(DesertMercenary::HolyFreeze), Difficulty::Nightmare),
    Variant(Class::DesertMercenary(DesertMercenary::Might), Difficulty::Nightmare),
    Variant(Class::DesertMercenary(DesertMercenary::Prayer), Difficulty::Hell),
    Variant(Class::DesertMercenary(DesertMercenary::Defiance), Difficulty::Hell),
    Variant(Class::DesertMercenary(DesertMercenary::BlessedAim), Difficulty::Hell),
    Variant(Class::IronWolf(IronWolf::Fire), Difficulty::Normal),
    Variant(Class::IronWolf(IronWolf::Cold), Difficulty::Normal),
    Variant(Class::IronWolf(IronWolf::Lightning), Difficulty::Normal),
    Variant(Class::IronWolf(IronWolf::Fire), Difficulty::Nightmare),
    Variant(Class::IronWolf(IronWolf::Cold), Difficulty::Nightmare),
    Variant(Class::IronWolf(IronWolf::Lightning), Difficulty::Nightmare),
    Variant(Class::IronWolf(IronWolf::Fire), Difficulty::Hell),
    Variant(Class::IronWolf(IronWolf::Cold), Difficulty::Hell),
    Variant(Class::IronWolf(IronWolf::Lightning), Difficulty::Hell),
    Variant(Class::Barbarian(Barbarian::Bash), Difficulty::Normal),
    Variant(Class::Barbarian(Barbarian::Bash), Difficulty::Normal),
    Variant(Class::Barbarian(Barbarian::Bash), Difficulty::Nightmare),
    Variant(Class::Barbarian(Barbarian::Bash), Difficulty::Nightmare),
    Variant(Class::Barbarian(Barbarian::Bash), Difficulty::Hell),
    Variant(Class::Barbarian(Barbarian::Bash), Difficulty::Hell),
    Variant(Class::DesertMercenary(DesertMercenary::Prayer), Difficulty::Nightmare),
    Variant(Class::DesertMercenary(DesertMercenary::Defiance), Difficulty::Nightmare),
    Variant(Class::DesertMercenary(DesertMercenary::BlessedAim), Difficulty::Nightmare),
    Variant(Class::DesertMercenary(DesertMercenary::Thorns), Difficulty::Hell),
    Variant(Class::DesertMercenary(DesertMercenary::HolyFreeze), Difficulty::Hell),
    Variant(Class::DesertMercenary(DesertMercenary::Might), Difficulty::Hell),
    Variant(Class::Barbarian(Barbarian::Frenzy), Difficulty::Normal),
    Variant(Class::Barbarian(Barbarian::Frenzy), Difficulty::Nightmare),
    Variant(Class::Barbarian(Barbarian::Frenzy), Difficulty::Hell),
];

pub const ROGUE_NAMES: [&str; 41] = [
    "Aliza", "Ampliza", "Annor", "Abhaya", "Elly", "Paige", "Basanti", "Blaise", "Kyoko",
    "Klaudia", "Kundri", "Kyle", "Visala", "Elexa", "Floria", "Fiona", "Gwinni", "Gaile", "Hannah",
    "Heather", "Iantha", "Diane", "Isolde", "Divo", "Ithera", "Itonya", "Liene", "Maeko", "Mahala",
    "Liaza", "Meghan", "Olena", "Oriana", "Ryann", "Rozene", "Raissa", "Sharyn", "Shikha", "Debi",
    "Tylena", "Wendy",
];

pub const DESERTMERCENARY_NAMES: [&str; 21] = [
    "Hazade", "Alhizeer", "Azrael", "Ahsab", "Chalan", "Haseen", "Razan", "Emilio", "Pratham",
    "Fazel", "Jemali", "Kasim", "Gulzar", "Mizan", "Leharas", "Durga", "Neeraj", "Ilzan",
    "Zanarhi", "Waheed", "Vikhyat",
];

pub const IRONWOLF_NAMES: [&str; 20] = [
    "Jelani", "Barani", "Jabari", "Devak", "Raldin", "Telash", "Ajheed", "Narphet", "Khaleel",
    "Phaet", "Geshef", "Vanji", "Haphet", "Thadar", "Yatiraj", "Rhadge", "Yashied", "Jarulf",
    "Flux", "Scorch",
];

pub const BARBARIAN_NAMES: [&str; 67] = [
    "Varaya",
    "Khan",
    "Klisk",
    "Bors",
    "Brom",
    "Wiglaf",
    "Hrothgar",
    "Scyld",
    "Healfdane",
    "Heorogar",
    "Halgaunt",
    "Hygelac",
    "Egtheow",
    "Bohdan",
    "Wulfgar",
    "Hild",
    "Heatholaf",
    "Weder",
    "Vikhyat",
    "Unferth",
    "Sigemund",
    "Heremod",
    "Hengest",
    "Folcwald",
    "Frisian",
    "Hnaef",
    "Guthlaf",
    "Oslaf",
    "Yrmenlaf",
    "Garmund",
    "Freawaru",
    "Eadgils",
    "Onela",
    "Damien",
    "Erfor",
    "Weohstan",
    "Wulf",
    "Bulwye",
    "Lief",
    "Magnus",
    "Klatu",
    "Drus",
    "Hoku",
    "Kord",
    "Uther",
    "Ip",
    "Ulf",
    "Tharr",
    "Kaelim",
    "Ulric",
    "Alaric",
    "Ethelred",
    "Caden",
    "Elgifu",
    "Tostig",
    "Alcuin",
    "Emund",
    "Sigurd",
    "Gorm",
    "Hollis",
    "Ragnar",
    "Torkel",
    "Wulfstan",
    "Alban",
    "Barloc",
    "Bill",
    "Theodoric",
];
